# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filtros.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(848, 580)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalAll = QtWidgets.QHBoxLayout()
        self.horizontalAll.setObjectName("horizontalAll")
        self.verticalSelect = QtWidgets.QVBoxLayout()
        self.verticalSelect.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalSelect.setObjectName("verticalSelect")
        self.horizontalMain = QtWidgets.QHBoxLayout()
        self.horizontalMain.setObjectName("horizontalMain")
        self.layoutGrado = QtWidgets.QVBoxLayout()
        self.layoutGrado.setObjectName("layoutGrado")
        self.comboGrado = QtWidgets.QComboBox(Form)
        self.comboGrado.setMaximumSize(QtCore.QSize(16777215, 20))
        self.comboGrado.setObjectName("comboGrado")
        self.comboGrado.addItem("")
        self.comboGrado.addItem("")
        self.layoutGrado.addWidget(self.comboGrado)
        self.combo1er = QtWidgets.QComboBox(Form)
        self.combo1er.setMaximumSize(QtCore.QSize(16777215, 20))
        self.combo1er.setObjectName("combo1er")
        self.combo1er.addItem("")
        self.combo1er.addItem("")
        self.combo1er.addItem("")
        self.combo1er.addItem("")
        self.layoutGrado.addWidget(self.combo1er)
        self.combo2do = QtWidgets.QComboBox(Form)
        self.combo2do.setMaximumSize(QtCore.QSize(16777215, 20))
        self.combo2do.setObjectName("combo2do")
        self.combo2do.addItem("")
        self.combo2do.addItem("")
        self.combo2do.addItem("")
        self.combo2do.addItem("")
        self.combo2do.addItem("")
        self.combo2do.addItem("")
        self.combo2do.addItem("")
        self.combo2do.addItem("")
        self.layoutGrado.addWidget(self.combo2do)
        self.horizontalMain.addLayout(self.layoutGrado)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushSimular = QtWidgets.QPushButton(Form)
        self.pushSimular.setMinimumSize(QtCore.QSize(0, 20))
        self.pushSimular.setObjectName("pushSimular")
        self.verticalLayout_3.addWidget(self.pushSimular)
        self.labelTipoFiltro = QtWidgets.QLabel(Form)
        self.labelTipoFiltro.setMaximumSize(QtCore.QSize(16777215, 13))
        self.labelTipoFiltro.setObjectName("labelTipoFiltro")
        self.verticalLayout_3.addWidget(self.labelTipoFiltro)
        self.horizontalMain.addLayout(self.verticalLayout_3)
        self.verticalSelect.addLayout(self.horizontalMain)
        self.layoutConfig = QtWidgets.QVBoxLayout()
        self.layoutConfig.setObjectName("layoutConfig")
        self.horizontalConfig = QtWidgets.QHBoxLayout()
        self.horizontalConfig.setObjectName("horizontalConfig")
        self.verticalConfigPolosCeros = QtWidgets.QVBoxLayout()
        self.verticalConfigPolosCeros.setObjectName("verticalConfigPolosCeros")
        self.layoutPolo = QtWidgets.QVBoxLayout()
        self.layoutPolo.setObjectName("layoutPolo")
        self.labelPolo = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPolo.sizePolicy().hasHeightForWidth())
        self.labelPolo.setSizePolicy(sizePolicy)
        self.labelPolo.setMaximumSize(QtCore.QSize(16777215, 13))
        self.labelPolo.setObjectName("labelPolo")
        self.layoutPolo.addWidget(self.labelPolo)
        self.complexPolo = QtWidgets.QHBoxLayout()
        self.complexPolo.setObjectName("complexPolo")
        self.spinBoxPolo = QtWidgets.QDoubleSpinBox(Form)
        self.spinBoxPolo.setDecimals(4)
        self.spinBoxPolo.setMinimum(-1000000000.0)
        self.spinBoxPolo.setMaximum(1000000000.0)
        self.spinBoxPolo.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinBoxPolo.setObjectName("spinBoxPolo")
        self.complexPolo.addWidget(self.spinBoxPolo)
        self.spinBoxPoloIm = QtWidgets.QDoubleSpinBox(Form)
        self.spinBoxPoloIm.setDecimals(4)
        self.spinBoxPoloIm.setMinimum(-1000000000.0)
        self.spinBoxPoloIm.setMaximum(1000000000.0)
        self.spinBoxPoloIm.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinBoxPoloIm.setObjectName("spinBoxPoloIm")
        self.complexPolo.addWidget(self.spinBoxPoloIm)
        self.layoutPolo.addLayout(self.complexPolo)
        self.horizontalPolo = QtWidgets.QHBoxLayout()
        self.horizontalPolo.setObjectName("horizontalPolo")
        self.checkPolo_cero = QtWidgets.QCheckBox(Form)
        self.checkPolo_cero.setObjectName("checkPolo_cero")
        self.horizontalPolo.addWidget(self.checkPolo_cero)
        self.checkPolo_infinito = QtWidgets.QCheckBox(Form)
        self.checkPolo_infinito.setObjectName("checkPolo_infinito")
        self.horizontalPolo.addWidget(self.checkPolo_infinito)
        self.layoutPolo.addLayout(self.horizontalPolo)
        self.complexPolo_2 = QtWidgets.QHBoxLayout()
        self.complexPolo_2.setObjectName("complexPolo_2")
        self.spinBoxPolo_2 = QtWidgets.QDoubleSpinBox(Form)
        self.spinBoxPolo_2.setDecimals(4)
        self.spinBoxPolo_2.setMinimum(-1000000000.0)
        self.spinBoxPolo_2.setMaximum(1000000000.0)
        self.spinBoxPolo_2.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinBoxPolo_2.setObjectName("spinBoxPolo_2")
        self.complexPolo_2.addWidget(self.spinBoxPolo_2)
        self.spinBoxPoloIm_2 = QtWidgets.QDoubleSpinBox(Form)
        self.spinBoxPoloIm_2.setDecimals(4)
        self.spinBoxPoloIm_2.setMinimum(-1000000000.0)
        self.spinBoxPoloIm_2.setMaximum(1000000000.0)
        self.spinBoxPoloIm_2.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinBoxPoloIm_2.setObjectName("spinBoxPoloIm_2")
        self.complexPolo_2.addWidget(self.spinBoxPoloIm_2)
        self.layoutPolo.addLayout(self.complexPolo_2)
        self.horizontalPolo_2 = QtWidgets.QHBoxLayout()
        self.horizontalPolo_2.setObjectName("horizontalPolo_2")
        self.checkPolo_cero_2 = QtWidgets.QCheckBox(Form)
        self.checkPolo_cero_2.setObjectName("checkPolo_cero_2")
        self.horizontalPolo_2.addWidget(self.checkPolo_cero_2)
        self.checkPolo_infinito_2 = QtWidgets.QCheckBox(Form)
        self.checkPolo_infinito_2.setObjectName("checkPolo_infinito_2")
        self.horizontalPolo_2.addWidget(self.checkPolo_infinito_2)
        self.layoutPolo.addLayout(self.horizontalPolo_2)
        self.verticalConfigPolosCeros.addLayout(self.layoutPolo)
        self.layoutCero = QtWidgets.QVBoxLayout()
        self.layoutCero.setObjectName("layoutCero")
        self.labelCero = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCero.sizePolicy().hasHeightForWidth())
        self.labelCero.setSizePolicy(sizePolicy)
        self.labelCero.setMaximumSize(QtCore.QSize(16777215, 13))
        self.labelCero.setObjectName("labelCero")
        self.layoutCero.addWidget(self.labelCero)
        self.complexCero = QtWidgets.QHBoxLayout()
        self.complexCero.setObjectName("complexCero")
        self.spinBoxCero = QtWidgets.QDoubleSpinBox(Form)
        self.spinBoxCero.setDecimals(4)
        self.spinBoxCero.setMinimum(-1000000000.0)
        self.spinBoxCero.setMaximum(1000000000.0)
        self.spinBoxCero.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinBoxCero.setObjectName("spinBoxCero")
        self.complexCero.addWidget(self.spinBoxCero)
        self.spinBoxCeroIm = QtWidgets.QDoubleSpinBox(Form)
        self.spinBoxCeroIm.setDecimals(4)
        self.spinBoxCeroIm.setMinimum(-1000000000.0)
        self.spinBoxCeroIm.setMaximum(1000000000.0)
        self.spinBoxCeroIm.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinBoxCeroIm.setObjectName("spinBoxCeroIm")
        self.complexCero.addWidget(self.spinBoxCeroIm)
        self.layoutCero.addLayout(self.complexCero)
        self.horizontalCero = QtWidgets.QHBoxLayout()
        self.horizontalCero.setObjectName("horizontalCero")
        self.checkCero_cero = QtWidgets.QCheckBox(Form)
        self.checkCero_cero.setObjectName("checkCero_cero")
        self.horizontalCero.addWidget(self.checkCero_cero)
        self.checkCero_infinito = QtWidgets.QCheckBox(Form)
        self.checkCero_infinito.setObjectName("checkCero_infinito")
        self.horizontalCero.addWidget(self.checkCero_infinito)
        self.layoutCero.addLayout(self.horizontalCero)
        self.complexCero_2 = QtWidgets.QHBoxLayout()
        self.complexCero_2.setObjectName("complexCero_2")
        self.spinBoxCero_2 = QtWidgets.QDoubleSpinBox(Form)
        self.spinBoxCero_2.setDecimals(4)
        self.spinBoxCero_2.setMinimum(-1000000000.0)
        self.spinBoxCero_2.setMaximum(1000000000.0)
        self.spinBoxCero_2.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinBoxCero_2.setObjectName("spinBoxCero_2")
        self.complexCero_2.addWidget(self.spinBoxCero_2)
        self.spinBoxCeroIm_2 = QtWidgets.QDoubleSpinBox(Form)
        self.spinBoxCeroIm_2.setDecimals(4)
        self.spinBoxCeroIm_2.setMinimum(-1000000000.0)
        self.spinBoxCeroIm_2.setMaximum(1000000000.0)
        self.spinBoxCeroIm_2.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinBoxCeroIm_2.setObjectName("spinBoxCeroIm_2")
        self.complexCero_2.addWidget(self.spinBoxCeroIm_2)
        self.layoutCero.addLayout(self.complexCero_2)
        self.horizontalCero_2 = QtWidgets.QHBoxLayout()
        self.horizontalCero_2.setObjectName("horizontalCero_2")
        self.checkCero_cero_2 = QtWidgets.QCheckBox(Form)
        self.checkCero_cero_2.setObjectName("checkCero_cero_2")
        self.horizontalCero_2.addWidget(self.checkCero_cero_2)
        self.checkCero_infinito_2 = QtWidgets.QCheckBox(Form)
        self.checkCero_infinito_2.setObjectName("checkCero_infinito_2")
        self.horizontalCero_2.addWidget(self.checkCero_infinito_2)
        self.layoutCero.addLayout(self.horizontalCero_2)
        self.verticalConfigPolosCeros.addLayout(self.layoutCero)
        self.horizontalConfig.addLayout(self.verticalConfigPolosCeros)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalConfig.addWidget(self.line)
        self.verticalConfigResto = QtWidgets.QVBoxLayout()
        self.verticalConfigResto.setObjectName("verticalConfigResto")
        self.layoutFrecCorte = QtWidgets.QVBoxLayout()
        self.layoutFrecCorte.setObjectName("layoutFrecCorte")
        self.labelFrecCorte = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFrecCorte.sizePolicy().hasHeightForWidth())
        self.labelFrecCorte.setSizePolicy(sizePolicy)
        self.labelFrecCorte.setMaximumSize(QtCore.QSize(16777215, 13))
        self.labelFrecCorte.setObjectName("labelFrecCorte")
        self.layoutFrecCorte.addWidget(self.labelFrecCorte)
        self.spinBoxFrecCorte = QtWidgets.QDoubleSpinBox(Form)
        self.spinBoxFrecCorte.setDecimals(4)
        self.spinBoxFrecCorte.setMinimum(-1000000000.0)
        self.spinBoxFrecCorte.setMaximum(1000000000.0)
        self.spinBoxFrecCorte.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinBoxFrecCorte.setProperty("value", 100.0)
        self.spinBoxFrecCorte.setObjectName("spinBoxFrecCorte")
        self.layoutFrecCorte.addWidget(self.spinBoxFrecCorte)
        self.spinBoxFrecCorte_2 = QtWidgets.QDoubleSpinBox(Form)
        self.spinBoxFrecCorte_2.setDecimals(4)
        self.spinBoxFrecCorte_2.setMinimum(-1000000000.0)
        self.spinBoxFrecCorte_2.setMaximum(1000000000.0)
        self.spinBoxFrecCorte_2.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinBoxFrecCorte_2.setProperty("value", 50.0)
        self.spinBoxFrecCorte_2.setObjectName("spinBoxFrecCorte_2")
        self.layoutFrecCorte.addWidget(self.spinBoxFrecCorte_2)
        self.verticalConfigResto.addLayout(self.layoutFrecCorte)
        self.layoutAmortiguamiento = QtWidgets.QVBoxLayout()
        self.layoutAmortiguamiento.setObjectName("layoutAmortiguamiento")
        self.labelAmortiguamiento = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAmortiguamiento.sizePolicy().hasHeightForWidth())
        self.labelAmortiguamiento.setSizePolicy(sizePolicy)
        self.labelAmortiguamiento.setMaximumSize(QtCore.QSize(16777215, 13))
        self.labelAmortiguamiento.setObjectName("labelAmortiguamiento")
        self.layoutAmortiguamiento.addWidget(self.labelAmortiguamiento)
        self.spinBoxAmortiguamiento = QtWidgets.QDoubleSpinBox(Form)
        self.spinBoxAmortiguamiento.setDecimals(4)
        self.spinBoxAmortiguamiento.setMinimum(-1000000000.0)
        self.spinBoxAmortiguamiento.setMaximum(1000000000.0)
        self.spinBoxAmortiguamiento.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinBoxAmortiguamiento.setProperty("value", 0.5)
        self.spinBoxAmortiguamiento.setObjectName("spinBoxAmortiguamiento")
        self.layoutAmortiguamiento.addWidget(self.spinBoxAmortiguamiento)
        self.spinBoxAmortiguamiento_2 = QtWidgets.QDoubleSpinBox(Form)
        self.spinBoxAmortiguamiento_2.setDecimals(4)
        self.spinBoxAmortiguamiento_2.setMinimum(-1000000000.0)
        self.spinBoxAmortiguamiento_2.setMaximum(1000000000.0)
        self.spinBoxAmortiguamiento_2.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinBoxAmortiguamiento_2.setProperty("value", 2.0)
        self.spinBoxAmortiguamiento_2.setObjectName("spinBoxAmortiguamiento_2")
        self.layoutAmortiguamiento.addWidget(self.spinBoxAmortiguamiento_2)
        self.verticalConfigResto.addLayout(self.layoutAmortiguamiento)
        self.layoutGanancia = QtWidgets.QVBoxLayout()
        self.layoutGanancia.setObjectName("layoutGanancia")
        self.labelGananciaBanda = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelGananciaBanda.sizePolicy().hasHeightForWidth())
        self.labelGananciaBanda.setSizePolicy(sizePolicy)
        self.labelGananciaBanda.setMaximumSize(QtCore.QSize(16777215, 13))
        self.labelGananciaBanda.setObjectName("labelGananciaBanda")
        self.layoutGanancia.addWidget(self.labelGananciaBanda)
        self.spinBoxGananciaBanda = QtWidgets.QDoubleSpinBox(Form)
        self.spinBoxGananciaBanda.setDecimals(4)
        self.spinBoxGananciaBanda.setMinimum(-1000000000.0)
        self.spinBoxGananciaBanda.setMaximum(1000000000.0)
        self.spinBoxGananciaBanda.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinBoxGananciaBanda.setProperty("value", 1.0)
        self.spinBoxGananciaBanda.setObjectName("spinBoxGananciaBanda")
        self.layoutGanancia.addWidget(self.spinBoxGananciaBanda)
        self.checkGananciaMaxima = QtWidgets.QCheckBox(Form)
        self.checkGananciaMaxima.setObjectName("checkGananciaMaxima")
        self.layoutGanancia.addWidget(self.checkGananciaMaxima)
        self.verticalConfigResto.addLayout(self.layoutGanancia)
        self.horizontalConfig.addLayout(self.verticalConfigResto)
        self.layoutConfig.addLayout(self.horizontalConfig)
        self.verticalSelect.addLayout(self.layoutConfig)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBodeMin = QtWidgets.QSpinBox(self.widget)
        self.spinBodeMin.setMinimum(-100)
        self.spinBodeMin.setMaximum(99)
        self.spinBodeMin.setProperty("value", -6)
        self.spinBodeMin.setObjectName("spinBodeMin")
        self.horizontalLayout.addWidget(self.spinBodeMin)
        self.spinBodeMax = QtWidgets.QSpinBox(self.widget)
        self.spinBodeMax.setMinimum(-99)
        self.spinBodeMax.setMaximum(100)
        self.spinBodeMax.setProperty("value", 6)
        self.spinBodeMax.setObjectName("spinBodeMax")
        self.horizontalLayout.addWidget(self.spinBodeMax)
        self.spinBodeTicks = QtWidgets.QSpinBox(self.widget)
        self.spinBodeTicks.setMinimum(1)
        self.spinBodeTicks.setMaximum(1000000000)
        self.spinBodeTicks.setProperty("value", 50000)
        self.spinBodeTicks.setDisplayIntegerBase(10)
        self.spinBodeTicks.setObjectName("spinBodeTicks")
        self.horizontalLayout.addWidget(self.spinBodeTicks)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(187, 204))
        self.label_2.setStyleSheet("border-image:url(:/rrr/index.jpg)")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spinGrafRtaTiempo = QtWidgets.QDoubleSpinBox(self.widget)
        self.spinGrafRtaTiempo.setDecimals(6)
        self.spinGrafRtaTiempo.setMinimum(1e-06)
        self.spinGrafRtaTiempo.setMaximum(1000000000.0)
        self.spinGrafRtaTiempo.setProperty("value", 20000.0)
        self.spinGrafRtaTiempo.setObjectName("spinGrafRtaTiempo")
        self.gridLayout_2.addWidget(self.spinGrafRtaTiempo, 0, 0, 1, 1)
        self.spinGrafRtaTicks = QtWidgets.QSpinBox(self.widget)
        self.spinGrafRtaTicks.setMinimum(1)
        self.spinGrafRtaTicks.setMaximum(1000000000)
        self.spinGrafRtaTicks.setProperty("value", 10000)
        self.spinGrafRtaTicks.setObjectName("spinGrafRtaTicks")
        self.gridLayout_2.addWidget(self.spinGrafRtaTicks, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        self.verticalSelect.addWidget(self.widget)
        self.horizontalAll.addLayout(self.verticalSelect)
        self.tabGraf = QtWidgets.QTabWidget(Form)
        self.tabGraf.setObjectName("tabGraf")
        self.tabBode = QtWidgets.QWidget()
        self.tabBode.setObjectName("tabBode")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabBode)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalBode = QtWidgets.QVBoxLayout()
        self.verticalBode.setObjectName("verticalBode")
        self.stackedBodeAmplitud = QtWidgets.QStackedWidget(self.tabBode)
        self.stackedBodeAmplitud.setObjectName("stackedBodeAmplitud")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedBodeAmplitud.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedBodeAmplitud.addWidget(self.page_2)
        self.verticalBode.addWidget(self.stackedBodeAmplitud)
        self.stackedBodeFase = QtWidgets.QStackedWidget(self.tabBode)
        self.stackedBodeFase.setObjectName("stackedBodeFase")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedBodeFase.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedBodeFase.addWidget(self.page_4)
        self.verticalBode.addWidget(self.stackedBodeFase)
        self.verticalLayout.addLayout(self.verticalBode)
        self.tabGraf.addTab(self.tabBode, "")
        self.tabPolosCeros = QtWidgets.QWidget()
        self.tabPolosCeros.setObjectName("tabPolosCeros")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabPolosCeros)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedPolosCeros = QtWidgets.QStackedWidget(self.tabPolosCeros)
        self.stackedPolosCeros.setObjectName("stackedPolosCeros")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.stackedPolosCeros.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.stackedPolosCeros.addWidget(self.page_6)
        self.verticalLayout_2.addWidget(self.stackedPolosCeros)
        self.tabGraf.addTab(self.tabPolosCeros, "")
        self.tabRespuesta = QtWidgets.QWidget()
        self.tabRespuesta.setObjectName("tabRespuesta")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabRespuesta)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalRespuesta = QtWidgets.QVBoxLayout()
        self.verticalRespuesta.setObjectName("verticalRespuesta")
        self.comboRespuesta = QtWidgets.QComboBox(self.tabRespuesta)
        self.comboRespuesta.setObjectName("comboRespuesta")
        self.comboRespuesta.addItem("")
        self.comboRespuesta.addItem("")
        self.comboRespuesta.addItem("")
        self.verticalRespuesta.addWidget(self.comboRespuesta)
        self.stackedWidget = QtWidgets.QStackedWidget(self.tabRespuesta)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.stackedWidget.addWidget(self.page_8)
        self.verticalRespuesta.addWidget(self.stackedWidget)
        self.verticalLayout_5.addLayout(self.verticalRespuesta)
        self.layoutRtaAmplitud = QtWidgets.QVBoxLayout()
        self.layoutRtaAmplitud.setObjectName("layoutRtaAmplitud")
        self.labelRtaAmplitud = QtWidgets.QLabel(self.tabRespuesta)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRtaAmplitud.sizePolicy().hasHeightForWidth())
        self.labelRtaAmplitud.setSizePolicy(sizePolicy)
        self.labelRtaAmplitud.setMaximumSize(QtCore.QSize(16777215, 13))
        self.labelRtaAmplitud.setObjectName("labelRtaAmplitud")
        self.layoutRtaAmplitud.addWidget(self.labelRtaAmplitud)
        self.spinBoxRtaAmplitud = QtWidgets.QDoubleSpinBox(self.tabRespuesta)
        self.spinBoxRtaAmplitud.setDecimals(4)
        self.spinBoxRtaAmplitud.setMinimum(0.0)
        self.spinBoxRtaAmplitud.setMaximum(1000000.0)
        self.spinBoxRtaAmplitud.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinBoxRtaAmplitud.setProperty("value", 1.0)
        self.spinBoxRtaAmplitud.setObjectName("spinBoxRtaAmplitud")
        self.layoutRtaAmplitud.addWidget(self.spinBoxRtaAmplitud)
        self.verticalLayout_5.addLayout(self.layoutRtaAmplitud)
        self.layoutRtaFrecuencia = QtWidgets.QVBoxLayout()
        self.layoutRtaFrecuencia.setObjectName("layoutRtaFrecuencia")
        self.labelRtaFrecuencia = QtWidgets.QLabel(self.tabRespuesta)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRtaFrecuencia.sizePolicy().hasHeightForWidth())
        self.labelRtaFrecuencia.setSizePolicy(sizePolicy)
        self.labelRtaFrecuencia.setMaximumSize(QtCore.QSize(16777215, 13))
        self.labelRtaFrecuencia.setObjectName("labelRtaFrecuencia")
        self.layoutRtaFrecuencia.addWidget(self.labelRtaFrecuencia)
        self.spinBoxRtaFrecuencia = QtWidgets.QDoubleSpinBox(self.tabRespuesta)
        self.spinBoxRtaFrecuencia.setDecimals(4)
        self.spinBoxRtaFrecuencia.setMinimum(0.0)
        self.spinBoxRtaFrecuencia.setMaximum(1000000000.0)
        self.spinBoxRtaFrecuencia.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinBoxRtaFrecuencia.setProperty("value", 200.0)
        self.spinBoxRtaFrecuencia.setObjectName("spinBoxRtaFrecuencia")
        self.layoutRtaFrecuencia.addWidget(self.spinBoxRtaFrecuencia)
        self.verticalLayout_5.addLayout(self.layoutRtaFrecuencia)
        self.layoutRtaFase = QtWidgets.QVBoxLayout()
        self.layoutRtaFase.setObjectName("layoutRtaFase")
        self.labelRtaFase = QtWidgets.QLabel(self.tabRespuesta)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRtaFase.sizePolicy().hasHeightForWidth())
        self.labelRtaFase.setSizePolicy(sizePolicy)
        self.labelRtaFase.setMaximumSize(QtCore.QSize(16777215, 13))
        self.labelRtaFase.setObjectName("labelRtaFase")
        self.layoutRtaFase.addWidget(self.labelRtaFase)
        self.spinBoxRtaFase = QtWidgets.QDoubleSpinBox(self.tabRespuesta)
        self.spinBoxRtaFase.setDecimals(4)
        self.spinBoxRtaFase.setMinimum(-380.0)
        self.spinBoxRtaFase.setMaximum(380.0)
        self.spinBoxRtaFase.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinBoxRtaFase.setObjectName("spinBoxRtaFase")
        self.layoutRtaFase.addWidget(self.spinBoxRtaFase)
        self.verticalLayout_5.addLayout(self.layoutRtaFase)
        self.layoutRtaPeriodo = QtWidgets.QVBoxLayout()
        self.layoutRtaPeriodo.setObjectName("layoutRtaPeriodo")
        self.labelRtaPeriodo = QtWidgets.QLabel(self.tabRespuesta)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRtaPeriodo.sizePolicy().hasHeightForWidth())
        self.labelRtaPeriodo.setSizePolicy(sizePolicy)
        self.labelRtaPeriodo.setMaximumSize(QtCore.QSize(16777215, 13))
        self.labelRtaPeriodo.setObjectName("labelRtaPeriodo")
        self.layoutRtaPeriodo.addWidget(self.labelRtaPeriodo)
        self.spinBoxRtaPeriodo = QtWidgets.QDoubleSpinBox(self.tabRespuesta)
        self.spinBoxRtaPeriodo.setDecimals(6)
        self.spinBoxRtaPeriodo.setMinimum(0.0)
        self.spinBoxRtaPeriodo.setMaximum(1000000.0)
        self.spinBoxRtaPeriodo.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinBoxRtaPeriodo.setProperty("value", 5.0)
        self.spinBoxRtaPeriodo.setObjectName("spinBoxRtaPeriodo")
        self.layoutRtaPeriodo.addWidget(self.spinBoxRtaPeriodo)
        self.verticalLayout_5.addLayout(self.layoutRtaPeriodo)
        self.layoutRtaDuty = QtWidgets.QVBoxLayout()
        self.layoutRtaDuty.setObjectName("layoutRtaDuty")
        self.labelRtaDuty = QtWidgets.QLabel(self.tabRespuesta)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRtaDuty.sizePolicy().hasHeightForWidth())
        self.labelRtaDuty.setSizePolicy(sizePolicy)
        self.labelRtaDuty.setMaximumSize(QtCore.QSize(16777215, 13))
        self.labelRtaDuty.setObjectName("labelRtaDuty")
        self.layoutRtaDuty.addWidget(self.labelRtaDuty)
        self.spinBoxRtaDuty = QtWidgets.QDoubleSpinBox(self.tabRespuesta)
        self.spinBoxRtaDuty.setDecimals(4)
        self.spinBoxRtaDuty.setMinimum(0.0)
        self.spinBoxRtaDuty.setMaximum(100.0)
        self.spinBoxRtaDuty.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinBoxRtaDuty.setProperty("value", 25.0)
        self.spinBoxRtaDuty.setObjectName("spinBoxRtaDuty")
        self.layoutRtaDuty.addWidget(self.spinBoxRtaDuty)
        self.verticalLayout_5.addLayout(self.layoutRtaDuty)
        self.tabGraf.addTab(self.tabRespuesta, "")
        self.horizontalAll.addWidget(self.tabGraf)
        self.horizontalLayout_5.addLayout(self.horizontalAll)

        self.retranslateUi(Form)
        self.tabGraf.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboGrado.setItemText(0, _translate("Form", "Primer Orden"))
        self.comboGrado.setItemText(1, _translate("Form", "Segundo Orden"))
        self.combo1er.setItemText(0, _translate("Form", "Pasa Bajos"))
        self.combo1er.setItemText(1, _translate("Form", "Pasa Altos"))
        self.combo1er.setItemText(2, _translate("Form", "Pasa Todo"))
        self.combo1er.setItemText(3, _translate("Form", "Arbitrario"))
        self.combo2do.setItemText(0, _translate("Form", "Pasa Bajos"))
        self.combo2do.setItemText(1, _translate("Form", "Pasa Altos"))
        self.combo2do.setItemText(2, _translate("Form", "Pasa Todo"))
        self.combo2do.setItemText(3, _translate("Form", "Pasa Banda"))
        self.combo2do.setItemText(4, _translate("Form", "Notch"))
        self.combo2do.setItemText(5, _translate("Form", "Low-pass Notch"))
        self.combo2do.setItemText(6, _translate("Form", "High-pass Notch"))
        self.combo2do.setItemText(7, _translate("Form", "Arbitrario"))
        self.pushSimular.setText(_translate("Form", "SIMULAR"))
        self.labelTipoFiltro.setText(_translate("Form", "Tipo de filtro"))
        self.labelPolo.setText(_translate("Form", "Polos"))
        self.checkPolo_cero.setText(_translate("Form", "Cero"))
        self.checkPolo_infinito.setText(_translate("Form", "Infinito"))
        self.checkPolo_cero_2.setText(_translate("Form", "Cero"))
        self.checkPolo_infinito_2.setText(_translate("Form", "Infinito"))
        self.labelCero.setText(_translate("Form", "Ceros"))
        self.checkCero_cero.setText(_translate("Form", "Cero"))
        self.checkCero_infinito.setText(_translate("Form", "Infinito"))
        self.checkCero_cero_2.setText(_translate("Form", "Cero"))
        self.checkCero_infinito_2.setText(_translate("Form", "Infinito"))
        self.labelFrecCorte.setText(_translate("Form", "Frecuencia de corte (rad/s)"))
        self.labelAmortiguamiento.setText(_translate("Form", "Razón de amortiguamiento"))
        self.labelGananciaBanda.setText(_translate("Form", "Ganancia"))
        self.checkGananciaMaxima.setText(_translate("Form", "Ganancia máxima"))
        self.label_3.setText(_translate("Form", "Graficar Bode entre:"))
        self.label.setText(_translate("Form", "Graficar respuesta hasta:"))
        self.label_2.setText(_translate("Form", "aprobado por el itbot"))
        self.spinGrafRtaTiempo.setSuffix(_translate("Form", " mseg"))
        self.tabGraf.setTabText(self.tabGraf.indexOf(self.tabBode), _translate("Form", "Bode"))
        self.tabGraf.setTabText(self.tabGraf.indexOf(self.tabPolosCeros), _translate("Form", "Polos y ceros"))
        self.comboRespuesta.setItemText(0, _translate("Form", "Senoide"))
        self.comboRespuesta.setItemText(1, _translate("Form", "Escalón"))
        self.comboRespuesta.setItemText(2, _translate("Form", "Pulso periódico"))
        self.labelRtaAmplitud.setText(_translate("Form", "Amplitud"))
        self.labelRtaFrecuencia.setText(_translate("Form", "Frecuencia (rad/s)"))
        self.labelRtaFase.setText(_translate("Form", "Fase (grados)"))
        self.labelRtaPeriodo.setText(_translate("Form", "Periodo (mseg)"))
        self.labelRtaDuty.setText(_translate("Form", "Duty Cycle"))
        self.tabGraf.setTabText(self.tabGraf.indexOf(self.tabRespuesta), _translate("Form", "Respuesta a señales"))
from src.resources.res import *


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
